### PR TITLE
Enable mention to comment authors

### PR DESCRIPTION
**Pull request by mocobeta**
#27 

Screenshot from 2022-07-17 14-03-02

should be

Screenshot from 2022-07-17 14-03-13

### CODE REVIEW

**Comment by mikemccand** [comment]
+1!

I think the screen shots are backwards maybe?  The top one is the new one (what this PR is doing) and bottom is the broken/old one?

Took me a bit to understand the change -- it looks like the placement of the [  ] was confusing GitHub markdown and then failing to render a link?

**Review by mikemccand — APPROVED** [review]

**Comment by mikemccand** [comment]
Also, I tried to dedup the `created on X updated on X` duplication (where X is the same), but I think I failed to doing the comparison after converting to date.  I'll open a separate PR to fix this.

**Comment by mikemccand** [comment]
OK sorry for the confusion -- now I think I understand -- the images ARE correct.  Should have let the caffeine sink it a little more before this ;)

@msokolov should not be a hyperlink.  I am curious though: does GitHub consider it a mention if @msokolov is included in the text of a hyperlink, in general (not that I want to do that here).

**Comment by mocobeta** [comment]
> I think the screen shots are backwards maybe? The top one is the new one (what this PR is doing) and bottom is the broken/old one?

No, the bottom one is the new one - the mention to the author is enabled. In the top one, the mention is veiled over by the hyperlink.

**Pull request merged**
